package com.oreilly.webservices;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for HttpClientExercise to verify basic structure and models.
 * Students can use this to check their implementations.
 */
class HttpClientExerciseTest {
    
    @Test
    void testExerciseInstantiation() {
        // Test that the exercise class can be created
        assertDoesNotThrow(() -> {
            HttpClientExercise exercise = new HttpClientExercise();
            assertNotNull(exercise);
        });
    }
    
    @Test
    void testTodoModelCreation() {
        // Test the Todo model functionality
        HttpClientExercise.Todo todo = new HttpClientExercise.Todo(1, "Test Todo", false);
        
        assertThat(todo.userId()).isEqualTo(1);
        assertThat(todo.title()).isEqualTo("Test Todo");
        assertThat(todo.completed()).isEqualTo(false);
        assertThat(todo.id()).isNull(); // Server sets ID
        
        // Test toString (automatically generated by record)
        assertThat(todo.toString()).contains("Test Todo");
    }
    
    @Test
    void testTodoWithId() {
        // Test creating todo with all fields including ID
        HttpClientExercise.Todo todo = new HttpClientExercise.Todo(100, 2, "Another Todo", true);
        
        assertThat(todo.id()).isEqualTo(100);
        assertThat(todo.userId()).isEqualTo(2);
        assertThat(todo.title()).isEqualTo("Another Todo");
        assertThat(todo.completed()).isEqualTo(true);
        
        // Test record equality and hashCode
        HttpClientExercise.Todo identical = new HttpClientExercise.Todo(100, 2, "Another Todo", true);
        assertThat(todo).isEqualTo(identical);
        assertThat(todo.hashCode()).isEqualTo(identical.hashCode());
    }
    
    @Test
    void testMainMethodDoesNotCrash() {
        // Test that main method can run without crashing
        // Note: This will show incomplete TODO messages since the exercise isn't complete
        assertDoesNotThrow(() -> HttpClientExercise.main(new String[]{}));
    }
}